### ISSUE TITLE
License configuration not published

### ISSUE THREAD

**Issue by FlorianMichael** [sugisaru/Needle#6]
Looks like you forgot to push your Intellij configuration for the license header, I would recommend to publish them on the repository (located in .idea/copyright) so people can use it in case they are planning on contributing via pull requests.

**Comment by sugisaru** [comment]
I'm not using IntelliJ IDEA anymore after 3 years, but tysm for the suggestion!

**Comment by sugisaru** [comment]
resolved through 823a874a84bdd2086eef1a8e10c6dd0100284c36 and 012d3033992583ba60f9b2fb38ee88f114f69b47
thank you for the issue!
